#!/bin/bash

_kill_procs() {
  kill -TERM $chromium
  wait $chromium
  kill -TERM $xvfb
}

# Setup a trap to catch SIGTERM and relay it to child processes
trap _kill_procs SIGTERM

XVFB_WHD=${XVFB_WHD:-1280x720x16}

# Start Xvfb
Xvfb :99 -ac -screen 0 $XVFB_WHD -nolisten tcp &
xvfb=$!

export DISPLAY=:99

chromium --no-sandbox --remote-debugging-port=9222 --user-data-dir=/tmp/hilalisa --disable-translate --disable-extensions --enable-dom-distiller  --vmodule=dom_distiller*=1 --disable-gpu --enable-distillability-service --enable-zero-copy --user-agent="Mozilla/5.0 (iPhone; CPU iPhone OS 10_3 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) CriOS/56.0.2924.75 Mobile/14E5239e Safari/602.1" --window-size="375,812" --window-position="0,0" --bwsi --disable-search-geolocation-disclosure --aggressive-cache-discard --aggressive-tab-discard --use-mobile-user-agent --user-data-dir --disable-web-security --cap-add=SYS_ADMIN chrome://dom-distiller" $@ &
chromium=$!

wait $chromium
wait $xvfb
